apiVersion: v1
kind: Secret
metadata:
  name: sftp-users
  namespace: prueba-invisia-docker
type: Opaque
stringData:
  users.conf: |
    kp:1001:PasswordKP
    dev:1002:PasswordDEV
    admin:1003:PasswordADMIN
